-- 코드를 입력하세요
SELECT
    P.PRODUCT_CODE, (SUM(SALES_AMOUNT) * PRICE) AS SALES
FROM
    PRODUCT AS P
    JOIN
    OFFLINE_SALE AS OS
    ON
    P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY
    OS.PRODUCT_ID
ORDER BY
    SALES DESC, P.PRODUCT_CODE ASC;