-- 코드를 작성해주세요
SELECT
    D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM
    DEVELOPERS AS D
WHERE
    (D.SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES GROUP BY CATEGORY HAVING CATEGORY = 'Front End')) != 0
ORDER BY
    D.ID ASC;