-- 코드를 입력하세요
SELECT
    p.MEMBER_ID, p.MEMBER_NAME, p.GENDER, DATE_FORMAT(p.DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM
    MEMBER_PROFILE p
WHERE
    p.GENDER = 'W'
    AND
    MONTH(p.DATE_OF_BIRTH) = 3
    AND
    p.TLNO IS NOT NULL
ORDER BY
    p.MEMBER_ID ASC;