-- 코드를 작성해주세요
SELECT
    SUM(SCORE) AS SCORE, HG.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM
    HR_GRADE AS HG
    LEFT JOIN
    HR_EMPLOYEES AS HE
    ON
    HG.EMP_NO = HE.EMP_NO
GROUP BY
    HG.EMP_NO
ORDER BY
    SCORE DESC
LIMIT
    1;