SELECT
    b.TITLE, r.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM
    USED_GOODS_REPLY r
    LEFT JOIN
    USED_GOODS_BOARD b
ON
    r.BOARD_ID = b.BOARD_ID
WHERE
    DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY
    r.CREATED_DATE ASC, b.TITLE ASC;